modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory (28 is current forge version)
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="simplevolcano" #mandatory
version="${version}" #mandatory
displayName="Simple Volcano" #mandatory
credits="" #optional
authors="TelepathicGrunt" #optional
description='''
A test with using noise to make volcanos through features'''